`define PRIV_U_LEVEL 2'b00
`define PRIV_S_LEVEL 2'b01
`define PRIV_M_LEVEL 2'b11

`define MTIME_INTERVAL 9


`define MACHINE_TIMER_INTERRUPT 31'd7

`define BREAKPOINT_EXCEPTION 31'd3
`define ENVIRONMENT_CALL_FROM_U 31'd8
`define ENVIRONMENT_CALL_FROM_S 31'd9
`define ENVIRONMENT_CALL_FROM_M 31'd11